### PR TITLE
updated name fields to make consistent, using slot-port format.

### PR DESCRIPTION
**Pull request by reidstidolph**
Per Abilash email proposal.

### CODE REVIEW

**Review by abilash128 — APPROVED** [review]

**Comment by drcosic** [comment]
[ ]  adding task so we do not merge till format is decided

**Review by jeffmart-jnpr — DISMISSED** [review]
We need to converge on the final change

**Comment by agrawalkaushik** [comment]
Need additional changes in wheeljack to support this. Do not merge until then.

**Comment by agrawalkaushik** [comment]
Please re-review this PR. We've made all the necessary changes to support the new `<type>-<slot>-<port>`. Wheeljack has been updated to support this format as well.

**Review by agrawalkaushik — APPROVED** [review]

**Review by drcosic — APPROVED** [review]

**Pull request merged**
